### ISSUE TITLE
Pixiv Login fails to load recaptcha if Pixiv Toolkit 5.0.0 is enabled

### ISSUE THREAD

**Issue by Pxartist** [leoding86/webextension-pixiv-toolkit#119]
**Describe the bug**
On first login, if Pixiv Toolkit 5.0.0 is enabled, Pixiv Login will fail to load a recaptcha, thereby preventing the user from logging in.

**Expected behavior**

User should be able to load recaptchas regardless of what extensions are active

**Example work from Pixiv**
If applicable, add work url to help me to reproduce the problem.

**Screenshots**

![Annotation 2021-07-31 171406](https://user-images.githubusercontent.com/26192313/127753606-bf4699a9-78e2-453d-bb12-74af58abc655.png)

**Browser and Version (please complete the following information):**
 - e.g. chrome, edge，firefox

Brave v 1.27.109

**Settings of extension**
You can export the settings of extension in setting page.

I am using ffmpeg, but that should not have an impact.

**Additional context**

To replicate a fresh login, delete all of the website's cookies. Afterwards, activate Pixiv Toolkit 5.0.0

**Comment by leoding86** [comment]
I noticed it. It is because ffmpeg need use SharedArrayBuffer to work. But after Chrome 92, the browser need `Cross-origin isolation` to use SharedArrayBuffer. The detail information is [here](https://developer.chrome.com/blog/enabling-shared-array-buffer/).

I'll fix the bug soon. The fix is, remove relative response headers when the page is not target page.

**Comment by leoding86** [comment]
Fix in 8169dced739eb85914774524f70a4d913d350009
