### ISSUE TITLE
Manga DLs aren't packed

### ISSUE THREAD

**Issue by scampadversary** [leoding86/webextension-pixiv-toolkit#125]
When I click the button to download all the images from a manga post, they save individually instead of in a .zip. (Illustration posts still properly download as .zips.)

I'm using Chrome version 92.0.4515.159.

**Comment by leoding86** [comment]
Issue confirmed.

**Comment by hal0thane** [comment]
The new version 5.0.3 does seem to fix the problem of packed files not packing correctly. Thank you. However, the extension is still creating extra subdirectories.

For example, since I started using the extension, I have always saved image id 12345678 by artist 998877 as `px-998877/998877-12345678_p000.jpg`.

This version (like 5.0.2) continues to save it as `px-998877/998877-12345678_p/998877-12345678_p000.jpg`.
If the work has more than one page, it is packed and saved correctly as `px-998877/998877-12345678_p.zip`.
It is also saved correctly if I turn on "Always pack" under the illustration section, but then I have to unzip the file afterward for every single image download.

**Comment by leoding86** [comment]
@hal0thane subdirectory is necessary. But I think I can add a setting in illustration setting section for users to decide if they need to create subdirectory.

**Comment by hal0thane** [comment]
That would be great if you could. Thanks. If not, then I will adapt.
