### ISSUE TITLE
[Feature Request]: Right click context menu to download illustration

### ISSUE THREAD

**Issue by takase1121** [leoding86/webextension-pixiv-toolkit#17]
It would be far more convenient to download illustrations; instead of having to move the cursor down to open the hidden bar and click "save illustration" users could just right click and download from there.

**Comment by leoding86** [comment]
I won't implement the featrue because some reasons. I'll try to explain the reason as simple as I can. First, the featrue you request is a context menu, and the menu should display in context menu when you visit Pixiv only. To implement this, I need to request extension "tabs" permission which is a very sensitive permission to users, because any extension have "tabs" permission will be granted ability to access user's all browser data, and this is not acceptable to many users. Lastest time I use the "tabs" permission to fix a bug made the extension recieve massive negative comments.
You can enable "Activate download panel automatically" setting in extension options page, then the bar you metioned will display automatically when the page is the target page.
