### ISSUE TITLE
Cant seem to download ugoira as apng

### ISSUE THREAD

**Issue by Question2** [leoding86/webextension-pixiv-toolkit#19]
I select the apng option, it starts generating, but when i check back later, the % indicator has dissapeared and I dont see any downloads...Firefox's download history shows nothing and I cant figure out if the add on has a specific download folder...

**Comment by leoding86** [comment]
Thanks for the feedback. Able to confirm that this issue occurs on Firefox if "Extension Takeover Download" is enabled. I will investigate again later.

**Comment by leoding86** [comment]
The downloads never start when setting "Extension Takeover Download" is enabled.

Because some security reason of Firefox, the add-on background script can't download the blob url which from other sites, but the generated image data is stored in the blob url. The only thing I can do is remove the download settings in Firefox version extension.

![#19](https://raw.githubusercontent.com/leoding86/image-storage/master/webext-pixiv-toolkit-issue%2319.jpg)
