### ISSUE TITLE
Some requests about renaming

### ISSUE THREAD

**Issue by timarupopoka** [leoding86/webextension-pixiv-toolkit#66]
1. For single image
I need another naming rule or an option to archive when the illustration only has one image.
"Keep page number" may be a setting for this, but it seems that switching this setting does not change anything.

2. Remove page number suffix
I want to exclude page numbers that are automatically added, such as "xxxxx_1-32.zip".

3. Enable folder
Using a format like "{author}\\{title}", allow the folder name to be included in rename settings.
At this time, specified folder should be created if it does not exist.

Specifically, I want to realize the following naming rules.
when multiple images:
```
{author}
  - [{author}]{title}.zip
    - 1.png
    - 2.png
    - ...
    - n.png
```
when single image:
```
{author}
  - [{author}]{title}.png
```
or
```
{author}
  - [{author}]{title}.zip
    - 1.png
```

**Comment by leoding86** [comment]
1. I can add a "Always pack illustrations" setting so that even if there is only one image in the illustration, it is always packaged into a zip file, and then you can achieve the second example of "When single image".
2. The suffix in there is used for prevent zip files with same name when there are multiple chunk. I think I can remove the suffix when all images is packed into one chunk.
3. You need place the "{author}" in "Save illustration in relative location" setting to achieve it.

**Comment by timarupopoka** [comment]
Thank you for considering my requests. #3 now works as I expected. I'm sorry for my overlooking.

**Comment by timarupopoka** [comment]
Hi, @leoding86 
I tried version 4.5.0 and # 2 hasn't been fixed.
There's no need to hurry, but I believe you remember it...
