### ISSUE TITLE
Redesign the history page

### ISSUE THREAD

**Issue by TestPolygon** [leoding86/webextension-pixiv-toolkit#80]
It looks like you have [abandoned](https://github.com/leoding86/webextension-pixiv-toolkit/issues/75#issuecomment-667625672) the old design of the history page. I see no way to enable it on the newly installed extension.

The old design had the questions, but the new one is not better.

The main problem that you use the infinite scrolling instead of the pagination. It absolutely inconvenient when you have a lot of entries.

Also I think it would be better to see no one entry for a row, but several (like it was). It allows to see the more entries at one moment.

Currently it looks so:

![Screenshot](https://user-images.githubusercontent.com/38364068/92778191-9b5ff080-f3a9-11ea-91f3-99942be6895d.png)

The type (`Illustration` in the screenshot) has significant emphasis, but it is the least important information. The date format `m/d/yyyy`? It's the missleading format. Displaying the full URL? – It looks unnesessary, it can be copied from the title ("Copy link address").

I think it would be better to display the bigger (a bit) image with the author name (+href) and the title (+href) under it. The date and work ID (not the full url) on hover (expand the cart to the bottom). Several entries at the row. And the pagination.

The date format `yyyy/mm/dd` is best suited for the archival purposes. And it's the offical format for Japan and China. Even for USA too: ["yyyy-mm-dd, are common or prescribed—particularly in military, academic, scientific, computing, industrial, or governmental contexts."](https://en.wikipedia.org/wiki/Date_format_by_country)

**Comment by leoding86** [comment]
There is a pagination issue which caused by indexeddb's limitation can't be resolved. So I remove the old style history and don't have a plan to bring it back.

I don't think the type tag is the least important information, maybe I'll add the setting for disabling display of the tag, but I keep it there, for now.

The size of thumbnail can't be perfect for everybody. Maybe I'll add a setting for leaving the choice to the users, but not for now. And I don't have plan to change the layout.

The date format is updated.
